image: node:latest

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - npm install
  cache:
    paths:
      - node_modules/
  artifacts:
    expire_in: 1 days
    when: on_success
    paths:
      - node_modules/

test:
  stage: test
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
  dependencies:
    - build
  script:
    - npm run test:ci
  cache:
    paths:
      - coverage/
  artifacts:
    paths:
      - coverage/
    when: always
    reports:
      junit:
        - junit.xml
      cobertura: coverage/cobertura-coverage.xml
  allow_failure: true

pages:
 stage: deploy
 dependencies:
    - test
 script:
    - cp -r coverage/* public
 artifacts:
   paths:
    - public
 only:
    - CI